# Basic Information 
title: Nan Lu
position: Assistant Professor
affiliation: University of Bristol
affiliation_link: https://www.bristol.ac.uk/
affiliation_logo: ./assets/img/bristol.png
email: lunan.bit (at) gmail.com

# Search Engine Optimization (SEO)
keywords: nan lu, lu nan
canonical: https://lunanbit.github.io
description: Nan Lu is an Assistant Professor in Artificial Intelligence at the University of Bristol. Her research focuses on trustworthy machine learning.


# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.co.jp/citations?user=KQUQlG4AAAAJ&hl=en
github_link: https://github.com/lunanbit
linkedin: https://www.linkedin.com/in/nan-lu-28b0991b6/
twitter: ""   # No Twitter

# Images 
avatar: ./assets/img/portrait.jpg

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
